// MCU internal program
#define INTERNAL_PROGRAM_IDLE   0
#define INTERNAL_PROGRAM_REMOVE_MEDIUM   1
#define INTERNAL_PROGRAM_RAMP_UP_PRESSURE   2   // 2 -> 3 always
#define INTERNAL_PROGRAM_PUMP_FLUID   3         // 3 -> 4 always 
#define INTERNAL_PROGRAM_EMPTY_FLUIDIC_LINE   4
#define INTERNAL_PROGRAM_PREUSE_CHECK_PRESSURE   5
#define INTERNAL_PROGRAM_PREUSE_CHECK_VACUUM   6
#define INTERNAL_PROGRAM_INITIAL 7
